# 这是一个帮助您开始使用 Actions 的基本工作流程

名称：CI

# 控制工作流程何时运行
在：
  # 在推送或拉取请求事件上触发工作流，但仅适用于“已弃用”分支# Triggers the workflow on push or pull request events but only for the "deprecated" branch
  push:
    branches: [[ “已弃用” ] “已弃用”  ]
  拉取请求：
    Branches : [    分支：[ “已弃用” ] “已弃用”  ]

  # 允许您从“操作”选项卡手动运行此工作流程# 允许您从“操作”选项卡手动运行此工作流程
  工作流程调度：

# 工作流运行由一个或多个可以顺序或并行运行的作业组成
工作：
  # 此工作流包含一个名为“build”的作业# 此工作流包含一个名为“build”的作业
  建造：
    # 运行该作业的运行器类型# 作业将运行的运行器的类型
    running-on :     运行于：ubuntu-latest

    # 步骤表示将作为作业的一部分执行的一系列任务# 步骤表示将作为作业的一部分执行的一系列任务
    脚步：
      # 签出$GITHUB_WORKSPACE下的存储库，方便你的工作可以访问它
      -用途：actions/checkout@v4

      # 使用 runners shell 运行单个命令
      -姓名：运行一行脚本
        休闲：echo 你好，世界！

      # 使用 runners shell 运行一组命令
      -姓名：运行多行脚本
        运行：|
          echo 添加其他操作以进行构建，
          echo 测试，并部署您的项目。
